language: python
python:
  - "2.7"

services:
  - docker

env:
  global:
    - TRAVIS_SECURE_ENV_VARS=true
    - DOCKER_USERNAME=jonascheng
    - secure: "AGdAoloP2GpqsQZuIIjU+fOaqkFPepTvVW81tpwhhuyoYTOz0Sgu+S9oW0tekBjMl+xoEEuy+KDLPhbgvPA/t8YAPFVxHLRE7fYJDZv43/5DzYJbX0l5GD6QXsE4qf6luj9rWh7Gb30ZvcU0BX2jBnsR5Ch5IyzssJOE8EJziknWCuc+xw2gqkF4KXB7IckUWU9R9RF99rrG3xyMhWjlrve1lEZzzjfPI41qAa19ydvT4UlQeAH3kvazjLD7O8hM2x+TZjAuKhlyLwgACD+Ja3npeIiOxh239lrztHtaiJ2pa+8drHCloQrPaGvUL92FFm7H5k6BcT4lw3bUDr/8F0e2zHMf87+uAA+LVQsFIPWNPyj4tMtDshz+HI66O+jqG0PHtvOCyk8Rm7/sZUhTcFUCmY7wikV6tq45bw6vLbksjSplOX33ReOdNhWVnF0gx8deQFLJXcZF3mSWPwViBPEisPK+Ub81KfJeWqLa+xB/blByvaf2p/+5fx67LsUOd1WOK4BmrUDlaBAi7p/01HVSnpQEi8jviVs1+NXGfvkEzUM8BhGjgvnwOX6c6LlPs5/WKuJd3cqhP+Q1b4DYtxSShLas/6OZPqton8G+gogEXl6GCBbJZOvtlSpkPXv04dRkeykzlphY1WN+p0e3dsfK5axobcHONRbZitEL90g="

before_install:
  - docker pull jonascheng/titan-on-dynamodb
  - pushd docker
  - pushd titan-on-dynamodb
  - docker build -t jonascheng/titan-on-dynamodb -f Dockerfile .
  - popd
  - popd

install:
  - docker-compose up -d

before_script:
  - pip install -r requirements.txt

script:
  - pushd tests
  - ./run_test.sh
  - popd

after_script:
  - docker-compose down

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push jonascheng/titan-on-dynamodb;
    fi